
create table t_kehadiran(
   id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
   id_siswa INT UNSIGNED NOT NULL,
   jam_masuk TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   jam_keluar TIMESTAMP NOT NULL DEFAULT NULL,
   status VARCHAR(255) DEFAULT NULL,
   PRIMARY KEY ( id )
);

create table t_murid(
   id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
   rfid_uid VARCHAR(255) NOT NULL,
   nama_siswa VARCHAR(255) NOT NULL,
   jurusan_dan_kelas VARCHAR(255) NOT NULL
   dibuat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( id )
);